# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Database migrations CLI tool
brew "golang-migrate"
# Powerful, lightweight programming language
brew "lua"
# Package manager for the Lua programming language
brew "luarocks"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Opinionated Lua code formatter
brew "stylua"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Incremental parsing library
brew "tree-sitter"
# Parser generator tool
brew "tree-sitter-cli"
# Internet file retriever
brew "wget"
cask "font-blex-mono-nerd-font"
cask "font-iosevka-charon-mono"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
