return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = {
          "bash",
          "css",
          "dockerfile",
          "fish",
          "html",
          "go",
          "javascript",
          "json",
          "jsonc",
          "lua",
          "markdown",
          "scss",
          "sql",
          "toml",
          "vim",
          "vimdoc",
          "yaml",
        },
        highlight = {
          "bash",
          "css",
          "dockerfile",
          "fish",
          "html",
          "go",
          "javascript",
          "json",
          "jsonc",
          "lua",
          "markdown",
          "scss",
          "sql",
          "toml",
          "vim",
          "vimdoc",
          "yaml",
        },
      })
    end,
  },
}
